#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "usage: $0 TRACE_OUTPUT_DIR" >&2
	exit 2
fi

DIR="$1"
TRACE="$DIR/trace.txt"
OUT="${CAPSCHED_TRACE_ANALYSIS_OUT:-$DIR/coverage-summary.md}"

if [[ ! -r "$TRACE" ]]; then
	echo "error: trace file not found: $TRACE" >&2
	exit 1
fi

count_name() {
	local name="$1"
	grep -Ec ":[[:space:]]+${name}([[:space:]:<({]|$)" "$TRACE" || true
}

mark() {
	local count="$1"
	if [[ "$count" -gt 0 ]]; then
		printf 'observed'
	else
		printf 'not_observed'
	fi
}

row() {
	local category="$1"
	local status="$2"
	local evidence="$3"
	local limitation="$4"
	printf '| `%s` | %s | %s | %s |\n' "$category" "$status" "$evidence" "$limitation"
}

cnt_try_to_wake_up="$(count_name try_to_wake_up)"
cnt_ttwu_runnable="$(count_name ttwu_runnable)"
cnt_ttwu_do_activate="$(count_name ttwu_do_activate)"
cnt_sched_ttwu_pending="$(count_name sched_ttwu_pending)"
cnt_ttwu_wakelist="$(count_name __ttwu_queue_wakelist)"
cnt_ttwu_queue="$(count_name ttwu_queue)"
cnt_wake_up_new_task="$(count_name wake_up_new_task)"
cnt_move_queued_task="$(count_name move_queued_task)"
cnt_enqueue_task="$(count_name enqueue_task)"
cnt_pick_next_task="$(count_name pick_next_task)"
cnt___pick_next_task="$(count_name __pick_next_task)"
cnt___schedule="$(count_name __schedule)"
cnt_sched_waking="$(count_name sched_waking)"
cnt_sched_wakeup="$(count_name sched_wakeup)"
cnt_sched_wakeup_new="$(count_name sched_wakeup_new)"
cnt_sched_switch="$(count_name sched_switch)"
cnt_sched_migrate_task="$(count_name sched_migrate_task)"

{
	printf '# Slice 0C Trace Coverage Summary\n\n'
	printf 'Generated by `%s`.\n\n' "$0"
	printf 'Trace directory:\n\n```text\n%s\n```\n\n' "$DIR"
	printf '## Boundary\n\n'
	printf 'This is trace coverage only. It is not RunCap enforcement evidence, DomainTag activation evidence, monitor-backed authority evidence, or hypervisor-grade isolation evidence.\n\n'

	printf '## Raw Counts\n\n'
	printf '| Target | Count |\n'
	printf '| --- | ---: |\n'
	printf '| `try_to_wake_up` | %s |\n' "$cnt_try_to_wake_up"
	printf '| `ttwu_runnable` | %s |\n' "$cnt_ttwu_runnable"
	printf '| `ttwu_do_activate` | %s |\n' "$cnt_ttwu_do_activate"
	printf '| `sched_ttwu_pending` | %s |\n' "$cnt_sched_ttwu_pending"
	printf '| `__ttwu_queue_wakelist` | %s |\n' "$cnt_ttwu_wakelist"
	printf '| `ttwu_queue` | %s |\n' "$cnt_ttwu_queue"
	printf '| `wake_up_new_task` | %s |\n' "$cnt_wake_up_new_task"
	printf '| `move_queued_task` | %s |\n' "$cnt_move_queued_task"
	printf '| `enqueue_task` | %s |\n' "$cnt_enqueue_task"
	printf '| `__pick_next_task` | %s |\n' "$cnt___pick_next_task"
	printf '| `pick_next_task` | %s |\n' "$cnt_pick_next_task"
	printf '| `__schedule` | %s |\n' "$cnt___schedule"
	printf '| `sched_waking` | %s |\n' "$cnt_sched_waking"
	printf '| `sched_wakeup` | %s |\n' "$cnt_sched_wakeup"
	printf '| `sched_wakeup_new` | %s |\n' "$cnt_sched_wakeup_new"
	printf '| `sched_switch` | %s |\n' "$cnt_sched_switch"
	printf '| `sched_migrate_task` | %s |\n\n' "$cnt_sched_migrate_task"

	printf '## Category Classification\n\n'
	printf '| Category | Status | Evidence | Limitation |\n'
	printf '| --- | --- | --- | --- |\n'
	row wake_try_to_wake_up "$(mark "$cnt_try_to_wake_up")" "try_to_wake_up=$cnt_try_to_wake_up, sched_waking=$cnt_sched_waking" "Function/event presence does not distinguish every branch."
	if [[ "$cnt_try_to_wake_up" -gt 0 ]]; then
		row wake_current_self ambiguous "try_to_wake_up=$cnt_try_to_wake_up" "No-code function tracing does not show whether p == current."
	else
		row wake_current_self not_observed "try_to_wake_up=0" "Could require a targeted workload or branch-specific kprobe/patch."
	fi
	row wake_already_runnable "$(mark "$cnt_ttwu_runnable")" "ttwu_runnable=$cnt_ttwu_runnable" "Entry confirms path reached, not whether all sub-branches executed."
	if [[ "$cnt_ttwu_runnable" -gt 0 && "$cnt_enqueue_task" -gt 0 ]]; then
		row wake_delayed_requeue ambiguous "ttwu_runnable=$cnt_ttwu_runnable, enqueue_task=$cnt_enqueue_task" "ENQUEUE_DELAYED flag is not visible in simple function tracing."
	else
		row wake_delayed_requeue not_inferable "ttwu_runnable=$cnt_ttwu_runnable, enqueue_task=$cnt_enqueue_task" "Needs argument capture, kprobe event, or explicit trace patch."
	fi
	row wake_local_activate "$(mark "$cnt_ttwu_do_activate")" "ttwu_do_activate=$cnt_ttwu_do_activate" "Remote pending activation also calls this path."
	row wake_remote_wakelist "$(mark "$cnt_ttwu_wakelist")" "__ttwu_queue_wakelist=$cnt_ttwu_wakelist" "Absence under one workload is not evidence that remote wake is irrelevant."
	row wake_remote_pending_activate "$(mark "$cnt_sched_ttwu_pending")" "sched_ttwu_pending=$cnt_sched_ttwu_pending" "Needs paired wakelist evidence for full remote path coverage."
	if [[ "$cnt_wake_up_new_task" -gt 0 || "$cnt_sched_wakeup_new" -gt 0 ]]; then
		row wake_new_task observed "wake_up_new_task=$cnt_wake_up_new_task, sched_wakeup_new=$cnt_sched_wakeup_new" "Does not cover SpawnCap semantics."
	else
		row wake_new_task not_observed "wake_up_new_task=0, sched_wakeup_new=0" "Needs fork/exec workload."
	fi
	if [[ "$cnt_move_queued_task" -gt 0 || "$cnt_sched_migrate_task" -gt 0 ]]; then
		row wake_queued_migration observed "move_queued_task=$cnt_move_queued_task, sched_migrate_task=$cnt_sched_migrate_task" "Migration reason and grant-staleness policy are not inferred."
	else
		row wake_queued_migration not_observed "move_queued_task=0, sched_migrate_task=0" "Needs affinity or load-balancing workload."
	fi
	row generic_enqueue "$(mark "$cnt_enqueue_task")" "enqueue_task=$cnt_enqueue_task" "Does not distinguish normal, delayed, migration, or restore flags."
	if [[ "$cnt___pick_next_task" -gt 0 ]]; then
		row pick_fair_fast ambiguous "__pick_next_task=$cnt___pick_next_task" "Simple function tracing cannot prove the fair fast branch."
		row pick_class_iteration ambiguous "__pick_next_task=$cnt___pick_next_task" "Simple function tracing cannot prove class-loop branch."
	else
		row pick_fair_fast not_observed "__pick_next_task=0" "Function target may be unavailable or workload insufficient."
		row pick_class_iteration not_observed "__pick_next_task=0" "Function target may be unavailable or workload insufficient."
	fi
	if [[ "$cnt_pick_next_task" -gt 0 ]]; then
		row pick_core_path ambiguous "pick_next_task=$cnt_pick_next_task" "Core scheduling state and force-idle branch are not visible."
	else
		row pick_core_path not_observed "pick_next_task=0" "May be compiled out, unavailable to ftrace, or workload insufficient."
	fi
	if [[ "$cnt___schedule" -gt 0 || "$cnt_sched_switch" -gt 0 ]]; then
		row switch_prev_next observed "__schedule=$cnt___schedule, sched_switch=$cnt_sched_switch" "Trace correlation is observational only."
	else
		row switch_prev_next not_observed "__schedule=0, sched_switch=0" "Trace setup likely failed or workload did not run."
	fi

	printf '\n## Missing Targets\n\n'
	if [[ -r "$DIR/missing-functions.txt" ]]; then
		printf 'Missing ftrace functions:\n\n```text\n'
		cat "$DIR/missing-functions.txt"
		printf '```\n\n'
	fi
	if [[ -r "$DIR/missing-events.txt" ]]; then
		printf 'Missing scheduler events:\n\n```text\n'
		cat "$DIR/missing-events.txt"
		printf '```\n\n'
	fi

	printf '## Required Follow-Up\n\n'
	printf 'Treat `not_observed`, `ambiguous`, and `not_inferable` entries as coverage gaps. They are not proof that a path is irrelevant.\n'
} > "$OUT"

printf 'Wrote %s\n' "$OUT"
